import { db } from './index';
import { activities } from './schema';

const activitiesData = [
  {
    id: '1',
    name: 'Visite guidée du Louvre',
    location: 'Paris, France',
    city: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    rating: 4.9,
    reviews: 3245,
    price: 45,
    duration: '3h',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
    category: 'Culture' as const,
    description: 'Découvrez les trésors du plus grand musée du monde',
    latitude: 48.8606,
    longitude: 2.3376,
  },
  {
    id: '2',
    name: 'Plongée sous-marine',
    location: 'Bali, Indonésie',
    city: 'Bali',
    region: 'Bali',
    country: 'Indonésie',
    rating: 4.8,
    reviews: 892,
    price: 80,
    duration: '4h',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    category: 'Aventure' as const,
    description: 'Explorez les récifs coralliens',
    latitude: -8.3405,
    longitude: 115.0920,
  },
  {
    id: '3',
    name: 'Safari en jeep',
    location: 'Serengeti, Tanzanie',
    city: 'Serengeti',
    region: 'Serengeti',
    country: 'Tanzanie',
    rating: 4.9,
    reviews: 1567,
    price: 150,
    duration: '8h',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
    category: 'Nature' as const,
    description: 'Observation de la faune sauvage',
    latitude: -2.3333,
    longitude: 34.8333,
  },
  {
    id: '4',
    name: 'Cours de cuisine locale',
    location: 'Tokyo, Japon',
    city: 'Tokyo',
    region: 'Kantō',
    country: 'Japon',
    rating: 4.7,
    reviews: 654,
    price: 70,
    duration: '3h',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    category: 'Gastronomie' as const,
    description: 'Apprenez à préparer des sushis authentiques',
    latitude: 35.6762,
    longitude: 139.6503,
  },
  {
    id: '5',
    name: 'Randonnée en montagne',
    location: 'Alpes, Suisse',
    city: 'Interlaken',
    region: 'Berne',
    country: 'Suisse',
    rating: 4.6,
    reviews: 432,
    price: 60,
    duration: '6h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    category: 'Sport' as const,
    description: 'Randonnée guidée avec vues panoramiques',
    latitude: 46.8182,
    longitude: 8.2275,
  },
  {
    id: '6',
    name: 'Tour de la Tour Eiffel',
    location: 'Paris, France',
    city: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    rating: 4.8,
    reviews: 8932,
    price: 35,
    duration: '2h',
    image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800',
    category: 'Culture' as const,
    description: 'Montez au sommet du monument le plus célèbre de Paris',
    latitude: 48.8584,
    longitude: 2.2945,
  },
  {
    id: '7',
    name: 'Balade en bateau-mouche',
    location: 'Paris, France',
    city: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    rating: 4.5,
    reviews: 2341,
    price: 25,
    duration: '1h30',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    category: 'Visites' as const,
    description: 'Découvrez Paris depuis la Seine',
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    id: '8',
    name: 'Visite de Montmartre',
    location: 'Paris, France',
    city: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    rating: 4.7,
    reviews: 1876,
    price: 30,
    duration: '3h',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
    category: 'Culture' as const,
    description: 'Explorez le quartier bohème de Paris',
    latitude: 48.8867,
    longitude: 2.3431,
  },
  {
    id: '9',
    name: 'Visite de la Cité de Carcassonne',
    location: 'Carcassonne, Occitanie',
    city: 'Carcassonne',
    region: 'Occitanie',
    country: 'France',
    rating: 4.9,
    reviews: 5432,
    price: 25,
    duration: '3h',
    image: 'https://images.unsplash.com/photo-1569949381669-ecf31ae8e613?w=800',
    category: 'Culture' as const,
    description: 'Découvrez la plus grande cité médiévale fortifiée d\'Europe',
    latitude: 43.2063,
    longitude: 2.3629,
  },
  {
    id: '10',
    name: 'Balade au Pont du Gard',
    location: 'Vers-Pont-du-Gard, Occitanie',
    city: 'Vers-Pont-du-Gard',
    region: 'Occitanie',
    country: 'France',
    rating: 4.8,
    reviews: 4321,
    price: 12,
    duration: '2h',
    image: 'https://images.unsplash.com/photo-1590955256807-a5b33dc08b55?w=800',
    category: 'Culture' as const,
    description: 'Aqueduc romain classé au patrimoine mondial de l\'UNESCO',
    latitude: 43.9475,
    longitude: 4.5357,
  },
  {
    id: '11',
    name: 'Tour en bateau sur le Canal du Midi',
    location: 'Toulouse, Occitanie',
    city: 'Toulouse',
    region: 'Occitanie',
    country: 'France',
    rating: 4.6,
    reviews: 2134,
    price: 35,
    duration: '2h30',
    image: 'https://images.unsplash.com/photo-1581888227599-779811939961?w=800',
    category: 'Visites' as const,
    description: 'Croisière sur le célèbre canal inscrit à l\'UNESCO',
    latitude: 43.6047,
    longitude: 1.4442,
  },
  {
    id: '12',
    name: 'Visite du Musée Toulouse-Lautrec',
    location: 'Albi, Occitanie',
    city: 'Albi',
    region: 'Occitanie',
    country: 'France',
    rating: 4.7,
    reviews: 1987,
    price: 18,
    duration: '2h',
    image: 'https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=800',
    category: 'Culture' as const,
    description: 'Plus grande collection d\'œuvres de Toulouse-Lautrec au monde',
    latitude: 43.9285,
    longitude: 2.1472,
  },
  {
    id: '13',
    name: 'Randonnée au Pic du Canigou',
    location: 'Pyrénées-Orientales, Occitanie',
    city: 'Prades',
    region: 'Occitanie',
    country: 'France',
    rating: 4.8,
    reviews: 876,
    price: 45,
    duration: '8h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    category: 'Sport' as const,
    description: 'Ascension du sommet emblématique de la Catalogne',
    latitude: 42.5186,
    longitude: 2.4561,
  },
  {
    id: '14',
    name: 'Exploration des Arènes de Nîmes',
    location: 'Nîmes, Occitanie',
    city: 'Nîmes',
    region: 'Occitanie',
    country: 'France',
    rating: 4.7,
    reviews: 3456,
    price: 15,
    duration: '2h',
    image: 'https://images.unsplash.com/photo-1576920360864-b702dd04f6b4?w=800',
    category: 'Culture' as const,
    description: 'Amphithéâtre romain le mieux conservé au monde',
    latitude: 43.8364,
    longitude: 4.3601,
  },
  {
    id: '15',
    name: 'Visite de la Place de la Comédie',
    location: 'Montpellier, Occitanie',
    city: 'Montpellier',
    region: 'Occitanie',
    country: 'France',
    rating: 4.5,
    reviews: 2789,
    price: 0,
    duration: '1h30',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    category: 'Visites' as const,
    description: 'Plus grande place piétonne d\'Europe',
    latitude: 43.6081,
    longitude: 3.8784,
  },
  {
    id: '16',
    name: 'Dégustation de vins à Collioure',
    location: 'Collioure, Occitanie',
    city: 'Collioure',
    region: 'Occitanie',
    country: 'France',
    rating: 4.9,
    reviews: 1543,
    price: 50,
    duration: '3h',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800',
    category: 'Gastronomie' as const,
    description: 'Dégustation de vins régionaux avec vue sur la Méditerranée',
    latitude: 42.5260,
    longitude: 3.0843,
  },
  {
    id: '17',
    name: 'Balade dans le Jardin Japonais',
    location: 'Toulouse, Occitanie',
    city: 'Toulouse',
    region: 'Occitanie',
    country: 'France',
    rating: 4.6,
    reviews: 1876,
    price: 8,
    duration: '1h30',
    image: 'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800',
    category: 'Nature' as const,
    description: 'Jardin zen au cœur de la ville rose',
    latitude: 43.5885,
    longitude: 1.4534,
  },
  {
    id: '18',
    name: 'Cité de l\'Espace',
    location: 'Toulouse, Occitanie',
    city: 'Toulouse',
    region: 'Occitanie',
    country: 'France',
    rating: 4.8,
    reviews: 5678,
    price: 28,
    duration: '4h',
    image: 'https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?w=800',
    category: 'Aventure' as const,
    description: 'Parc à thème dédié à l\'espace et à la conquête spatiale',
    latitude: 43.5864,
    longitude: 1.4931,
  },
  {
    id: '19',
    name: 'Visite du Palais des Papes',
    location: 'Avignon, Provence',
    city: 'Avignon',
    region: 'Provence-Alpes-Côte d\'Azur',
    country: 'France',
    rating: 4.7,
    reviews: 4123,
    price: 20,
    duration: '2h30',
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800',
    category: 'Culture' as const,
    description: 'Plus grand palais gothique du monde',
    latitude: 43.9513,
    longitude: 4.8075,
  },
  {
    id: '20',
    name: 'Plage et sports nautiques',
    location: 'Perpignan, Occitanie',
    city: 'Perpignan',
    region: 'Occitanie',
    country: 'France',
    rating: 4.5,
    reviews: 1234,
    price: 40,
    duration: '5h',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    category: 'Plage' as const,
    description: 'Activités nautiques sur les plages catalanes',
    latitude: 42.6887,
    longitude: 2.8948,
  },
];

export async function seedActivities() {
  console.log('[Seed] Starting activities seed...');

  try {
    for (const activity of activitiesData) {
      await db.insert(activities).values({
        ...activity,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
      console.log(`[Seed] Inserted activity: ${activity.name}`);
    }

    console.log('[Seed] Activities seed completed successfully!');
  } catch (error) {
    console.error('[Seed] Error seeding activities:', error);
    throw error;
  }
}

if (require.main === module) {
  seedActivities()
    .then(() => {
      console.log('[Seed] Done');
      process.exit(0);
    })
    .catch((error) => {
      console.error('[Seed] Failed:', error);
      process.exit(1);
    });
}
